const ADD_NEW_FOOD_ITEM = "ADD_NEW_FOOD_ITEM";
const INCREASE_PRICE = "INCREASE_PRICE";
const INCREASE_QUANTITY = "INCREASE_QUANTITY";
const REMOVE_ITEM = "REMOVE_ITEM";
const UPDATE_TIP = "UPDATE_TIP";

export {
  ADD_NEW_FOOD_ITEM,
  INCREASE_PRICE,
  INCREASE_QUANTITY,
  REMOVE_ITEM,
  UPDATE_TIP,
};
